import './css/bootstrap/bootstrap-grid.min.css';
import './css/bootstrap/bootstrap-reboot.min.css';
import './css/bootstrap/bootstrap.min.css';
import './js/index';
import './css/startScreen/index.css';
import './css/tutorial/index.css';
import './css/left-menu/index.css';
import './css/right-form/index.css';
import './css/total-form/index.css';
